# Problem Set 3



Team: 
    Lea Schmierer 3546563;
    Angelina Basova 3704658;
    Daniel Knorr 3727033

## Exercise 1


## Exercise 2

## Exercise 3

## Exercise 4

In [50]:
try:
    import numpy
except:
    print("This implementation requires the numpy module.")
    exit(0)

###############################################################################

"""
@INPUT:
    R     : a matrix to be factorized, dimension N x M
    P     : an initial matrix of dimension N x K
    Q     : an initial matrix of dimension M x K
    K     : the number of latent features
    steps : the maximum number of steps to perform the optimisation
    alpha : the learning rate
    beta  : the regularization parameter
@OUTPUT:
    the final matrices P and Q
"""
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001:
            break
    return P, Q.T

###############################################################################

if __name__ == "__main__":
    R = [
         #[5,3,0,1],
         #[4,0,0,1],
         #[1,1,0,5],
         #[1,0,0,4],
         #[0,1,5,4],
         [1,0,2,0,0,1],
         [0,0,4,2,0,0],
         [3,5,0,4,4,3],
         [0,4,1,0,3,0],
         [0,0,2,5,4,3],
         [5,0,0,0,2,0],
         [0,4,3,0,0,0],
         [0,0,0,4,0,2],
         [5,0,4,0,0,0],
         [0,2,3,0,0,0],
         [4,2,5,2,2,4],
         [0,3,0,0,5,0,],
        ]

    R = numpy.array(R)

    N = len(R)
    M = len(R[0])
    K = 2

    P = numpy.random.rand(N,K)
    Q = numpy.random.rand(M,K)

    nP, nQ = matrix_factorization(R, P, Q, K)
    nR= numpy.dot(nP, nQ.T)


    print('R')
    print(R)

    print('P')
    print(nP)

    print('Q')
    print(nQ.T)


    print('gesamt')
    print (nR)



R
[[1 0 2 0 0 1]
 [0 0 4 2 0 0]
 [3 5 0 4 4 3]
 [0 4 1 0 3 0]
 [0 0 2 5 4 3]
 [5 0 0 0 2 0]
 [0 4 3 0 0 0]
 [0 0 0 4 0 2]
 [5 0 4 0 0 0]
 [0 2 3 0 0 0]
 [4 2 5 2 2 4]
 [0 3 0 0 5 0]]
P
[[0.44465943 1.50779204 0.6061574  0.06917856 0.42806438 2.11583779
  0.89069682 0.30309164 1.55263095 1.06395122 1.74360231 2.41346891]
 [0.4604067  0.5017197  1.86876666 1.6392827  2.12269132 0.04683857
  1.55809612 1.69417719 1.13950349 0.70931503 0.46338354 1.16915103]]
Q
[[2.28483506 0.24378029 2.5023561  0.58765869 0.97258029 1.95956313]
 [0.87493703 2.43393196 0.47854722 2.14451983 1.79168065 0.93845185]]
gesamt
[[1.41880032 1.2289978  1.33302257 1.24865929 1.25736878 1.30340774]
 [3.88402927 1.58872159 4.01312918 1.96201494 2.3653703  3.42545348]
 [3.02002283 4.69622012 2.41111475 4.36382083 3.93776979 2.94155122]
 [1.59233073 4.00676693 0.95758356 3.55612765 3.00435279 1.67394763]
 [2.83527775 5.27083991 2.08697754 4.8037094  4.21951194 2.83086277]
 [4.87532116 0.62980142 5.31699407 1.34383669 2

In [2]:
#b)

## Exercise 5

## Exercise 6 Bonus